### ISSUE TITLE
@FunctionalInterface 该注解未定义？

### ISSUE THREAD

**Issue by 395779222** [a2888409/face2face#3]

**Comment by a2888409** [comment]
1、需要jdk 1.8
2、打开project structure，选择Projects，设置language level为：8-Lambdas
参考：http://blog.csdn.net/tiantiandjava/article/details/46311929

**Comment by a2888409** [comment]
1、需要jdk 1.8
2、打开project structure，选择Projects，设置language level为：8-Lambdas
参考：http://blog.csdn.net/tiantiandjava/article/details/46311929
