### ISSUE TITLE
redis问题

### ISSUE THREAD

**Issue by czhyinshen** [a2888409/face2face#5]
你好博主，根据你的步骤在redis-server.exe  redis.windos.conf时候报了redis-server.exe  redis.windos.conf的错误，新手一名求指导

**Comment by a2888409** [comment]
这个问题请自行百度windows下搭建redis，这是我找到的一篇博文http://www.cnblogs.com/linjiqin/archive/2013/05/27/3101694.html
假如你有linux系统，最后能在linux上安装一个redis
