### ISSUE TITLE
这个works 意图是什么呢

### ISSUE THREAD

**Issue by OMGgogong** [a2888409/face2face#9]
Netty 自带一个executionhandler 是不是同样也会开启一个线程处理紧接着的handler 。请大神说一说这个works 的妙用！ 说的尽量详细点 先谢过！！

**Comment by a2888409** [comment]
之所以需要额外的工作线程是由Netty的线程模型决定的，通常来说，对于比较复杂耗时的业务逻辑不推荐在接收消息的IO线程，即pipeline内的handler处理，这样可能会造成任务的阻塞。
IO线程通常只处理比较简单的任务，workers工作线程可以用Netty提供的DefaultEventExecutor或者自带的其他线程池实现替代，他们的作用是相同的，都是作为工作线程池处理任务。
IO线程和工作线程的分离，能够充分的保证异步，高效的执行任务。
